version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=123123
      - indices.query.bool.max_clause_count=100000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    container_name: es
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
      - "./plugins:/usr/share/elasticsearch/plugins"
    restart: always
    deploy:
      resources:
        limits:
          memory: 3G
volumes:
  esdata:
    driver: local